/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class DirichletCharacter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DirichletCharacter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DirichletCharacter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_DirichletCharacter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setN(long value) {
    arblibJNI.DirichletCharacter_n_set(swigCPtr, this, value);
  }

  public long getN() {
    return arblibJNI.DirichletCharacter_n_get(swigCPtr, this);
  }

  public void setLog(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.DirichletCharacter_log_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getLog() {
    long cPtr = arblibJNI.DirichletCharacter_log_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public DirichletCharacter() {
    this(arblibJNI.new_DirichletCharacter(), true);
  }

}
