/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class DirichletGroup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DirichletGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DirichletGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_DirichletGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setQ(long value) {
    arblibJNI.DirichletGroup_q_set(swigCPtr, this, value);
  }

  public long getQ() {
    return arblibJNI.DirichletGroup_q_get(swigCPtr, this);
  }

  public void setQ_even(long value) {
    arblibJNI.DirichletGroup_q_even_set(swigCPtr, this, value);
  }

  public long getQ_even() {
    return arblibJNI.DirichletGroup_q_even_get(swigCPtr, this);
  }

  public void setMod(SWIGTYPE_p_nmod_t value) {
    arblibJNI.DirichletGroup_mod_set(swigCPtr, this, SWIGTYPE_p_nmod_t.getCPtr(value));
  }

  public SWIGTYPE_p_nmod_t getMod() {
    return new SWIGTYPE_p_nmod_t(arblibJNI.DirichletGroup_mod_get(swigCPtr, this), true);
  }

  public void setRad_q(long value) {
    arblibJNI.DirichletGroup_rad_q_set(swigCPtr, this, value);
  }

  public long getRad_q() {
    return arblibJNI.DirichletGroup_rad_q_get(swigCPtr, this);
  }

  public void setPhi_q(long value) {
    arblibJNI.DirichletGroup_phi_q_set(swigCPtr, this, value);
  }

  public long getPhi_q() {
    return arblibJNI.DirichletGroup_phi_q_get(swigCPtr, this);
  }

  public void setNeven(int value) {
    arblibJNI.DirichletGroup_neven_set(swigCPtr, this, value);
  }

  public int getNeven() {
    return arblibJNI.DirichletGroup_neven_get(swigCPtr, this);
  }

  public void setNum(int value) {
    arblibJNI.DirichletGroup_num_set(swigCPtr, this, value);
  }

  public int getNum() {
    return arblibJNI.DirichletGroup_num_get(swigCPtr, this);
  }

  public void setExpo(long value) {
    arblibJNI.DirichletGroup_expo_set(swigCPtr, this, value);
  }

  public long getExpo() {
    return arblibJNI.DirichletGroup_expo_get(swigCPtr, this);
  }

  public void setP(DirichletPrimeGroup value) {
    arblibJNI.DirichletGroup_P_set(swigCPtr, this, DirichletPrimeGroup.getCPtr(value), value);
  }

  public DirichletPrimeGroup getP() {
    long cPtr = arblibJNI.DirichletGroup_P_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DirichletPrimeGroup(cPtr, false);
  }

  public void setGenerators(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.DirichletGroup_generators_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getGenerators() {
    long cPtr = arblibJNI.DirichletGroup_generators_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public void setPHI(SWIGTYPE_p_unsigned_long value) {
    arblibJNI.DirichletGroup_PHI_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getPHI() {
    long cPtr = arblibJNI.DirichletGroup_PHI_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public DirichletGroup() {
    this(arblibJNI.new_DirichletGroup(), true);
  }

}
