/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class FoundRoots {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public FoundRoots(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(FoundRoots obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_FoundRoots(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFound(FloatInterval value) {
    arblibJNI.FoundRoots_found_set(swigCPtr, this, FloatInterval.getCPtr(value), value);
  }

  public FloatInterval getFound() {
    long cPtr = arblibJNI.FoundRoots_found_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FloatInterval(cPtr, false);
  }

  public void setFlags(SWIGTYPE_p_int value) {
    arblibJNI.FoundRoots_flags_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getFlags() {
    long cPtr = arblibJNI.FoundRoots_flags_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public FoundRoots() {
    this(arblibJNI.new_FoundRoots(), true);
  }

}
