/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

import static arblib.Constants.*;

public class FoundRoots implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public FoundRoots(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(FoundRoots obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_FoundRoots(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  int n;
  
  @Override
  public void close()
  {
    for (int i = 0; i < n; i++)
    {
      // TODO: enable array of interval access and call arf_interval_clear on each
    }
    arblib.flint_free(new SWIGTYPE_p_void(FloatInterval.getCPtr(getFound()),
                                          false));
    arblib.flint_free(new SWIGTYPE_p_void(SWIGTYPE_p_int.getCPtr(getFlags()),
                                          false));
    delete();
                                          
  }

  

  public void setFound(FloatInterval value) {
    arblibJNI.FoundRoots_found_set(swigCPtr, this, FloatInterval.getCPtr(value), value);
  }

  public FloatInterval getFound() {
    long cPtr = arblibJNI.FoundRoots_found_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FloatInterval(cPtr, false);
  }

  public void setFlags(SWIGTYPE_p_int value) {
    arblibJNI.FoundRoots_flags_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getFlags() {
    long cPtr = arblibJNI.FoundRoots_flags_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public FoundRoots() {
    this(arblibJNI.new_FoundRoots(), true);
  }

}
