/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

import org.vibur.objectpool.ConcurrentPool;
import org.vibur.objectpool.PoolService;
import org.vibur.objectpool.util.ConcurrentLinkedQueueCollection;

public class Magnitude implements AutoCloseable,Comparable<Magnitude> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Magnitude(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Magnitude obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_Magnitude(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

 PoolService<Magnitude> poolService;
 
 public Magnitude( PoolService<Magnitude> poolService ) {
  this(arblibJNI.new_Magnitude(), true);
  this.poolService = poolService;
 }

  @Override
  public void close()
  { 
   if (poolService != null)
    {
      poolService.restore(this);
    }
    else
    {
      delete();
    }
  }

  static final PoolService<Magnitude> pool = new ConcurrentPool<>(new ConcurrentLinkedQueueCollection<>(),
                                                             	  new MagnitudeFactory(),
                                                             	  100,
                                                             	  100000000,
                                                             	  false,
                                                             	  new MagnitudeListener() );

  public static Magnitude claim()
  {
    Magnitude r = pool.take();
    r.poolService = pool;
    return r;
  }
  
  @Override
  public int compareTo( Magnitude other )
  {
    return arblib.mag_cmp( this, other );
  }
  
  public Magnitude pow( long y, Magnitude res )
  {
    arblib.mag_pow_ui(res, this, y);
    return res;
  }
  
  public Magnitude mul(Magnitude b, Magnitude res)
  {
    arblib.mag_mul(res, this, b );
    return res;    
  }
  
  public Magnitude add(Magnitude u, Magnitude res)
  {
    arblib.mag_add(res, this, u);
    return res;
  }
    
  public Magnitude zero()
  {
    arblib.mag_zero(this);
    return this;
  }
  
  

  public void setExp(SWIGTYPE_p_fmpz value) {
    arblibJNI.Magnitude_exp_set(swigCPtr, this, SWIGTYPE_p_fmpz.getCPtr(value));
  }

  public SWIGTYPE_p_fmpz getExp() {
    return new SWIGTYPE_p_fmpz(arblibJNI.Magnitude_exp_get(swigCPtr, this), true);
  }

  public void setMan(SWIGTYPE_p_mp_limb_t value) {
    arblibJNI.Magnitude_man_set(swigCPtr, this, SWIGTYPE_p_mp_limb_t.getCPtr(value));
  }

  public SWIGTYPE_p_mp_limb_t getMan() {
    return new SWIGTYPE_p_mp_limb_t(arblibJNI.Magnitude_man_get(swigCPtr, this), true);
  }

  public Magnitude() {
    this(arblibJNI.new_Magnitude(), true);
  }

}
