/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

import static arblib.Constants.*;

public class RealFunctionParams implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public RealFunctionParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(RealFunctionParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_RealFunctionParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  @Override
  public void close()
  { 
      delete();
  }

  

  public void setRealFunction(java.lang.Object value) {
    arblibJNI.RealFunctionParams_realFunction_set(swigCPtr, this, value);
  }

  public java.lang.Object getRealFunction() {
    return arblibJNI.RealFunctionParams_realFunction_get(swigCPtr, this);
  }

  public void setZ(java.lang.Object value) {
    arblibJNI.RealFunctionParams_z_set(swigCPtr, this, value);
  }

  public java.lang.Object getZ() {
    return arblibJNI.RealFunctionParams_z_get(swigCPtr, this);
  }

  public void setW(java.lang.Object value) {
    arblibJNI.RealFunctionParams_w_set(swigCPtr, this, value);
  }

  public java.lang.Object getW() {
    return arblibJNI.RealFunctionParams_w_get(swigCPtr, this);
  }

  public RealFunctionParams() {
    this(arblibJNI.new_RealFunctionParams(), true);
  }

}
