/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arblib;

public class SWIGTYPE_p_arf_interval_ptr {
  private transient long swigCPtr;

  public SWIGTYPE_p_arf_interval_ptr(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  public SWIGTYPE_p_arf_interval_ptr() {
    swigCPtr = 0;
  }

  public static long getCPtr(SWIGTYPE_p_arf_interval_ptr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

